### ISSUE TITLE
FATA stat /var/run/pmon2/pmon2.sock: no such file or directory

### ISSUE THREAD

**Issue by lanyulei** [ntt360/pmon2#1]

**Comment by apptut** [comment]
能给我一些详细的反馈信息吗？
1. 安装的操作系统是？
2. 执行什么操作产生的这个错误呢？

**Comment by apptut** [comment]
you need start the pmond process when use pmon2 the first time。

```bash
# centos6
sudo initctl start pmond

# centos7
sudo systemctl start pmond
```

then, you can use `sudo pmon2 run [process]`，the pmond process for monitor the run process state, but it's not start auto when first installed
