### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by pizixi** [ntt360/pmon2#11]
手动kill掉进程，pmon2 ls 看进程还在，然后restart 该进程也异常了

**Comment by apptut** [comment]
[](url)@pizixi 可否提供具体的操作以及进程日志？

1. pmon2 版本？
2. 具体操作步骤？
3. 进程日志？pmon2 logf [进程id]

一般来说手动Kill进程后，pmon2会尝试自动拉起进程（除非你的进程一直重启失败），可以观察整个过程中的进程id，我这边演示没有问题。截图如下：
<img width="1312" alt="WX20220725-233823@2x" src="https://user-images.githubusercontent.com/1408202/180819857-34c5f6b9-6ce1-41d3-b5d2-860b61706c9f.png">

**Comment by pizixi** [comment]
我这kill -9 去杀进程的，杀完，进程没了，但是pmon2 ls 看还是running，pid还是之前的pid，但是实际没有这个进程了

**Comment by apptut** [comment]
@pizixi 能否给个二进制包？二进制包我也看不到你的代码

**Comment by pizixi** [comment]
![image](https://user-images.githubusercontent.com/56673215/181137822-1414feeb-0a19-453f-925b-8b20991e71a0.png)

**Comment by pizixi** [comment]
用的就是这个开源的软件PPGO_JOB，改了一点点代码而已

**Comment by apptut** [comment]
@pizixi 自己装了下这个PPGO_JOB，没能复现你说的BUG，能够告知你使用的操作系统？和pmon2版本？本次测试我使用的是：CentOS7.4，pmon2:1.20
<img width="1069" alt="screen" src="https://user-images.githubusercontent.com/1408202/181294123-31221db3-388b-4aaf-8703-950e16431c68.png">

**Comment by pizixi** [comment]
奇了怪了，我也是centos7，版本 CentOS Linux release 7.2.1511 (Core) 
![image](https://user-images.githubusercontent.com/56673215/181512302-f72b5b8d-bcc4-4989-b3d5-f31ee0cc1cdf.png)
pmon2 版本问题？

**Comment by pizixi** [comment]
Releases 里面版本rpm包显示1.12.0，上面又显示1.20.1，乱了

**Comment by apptut** [comment]
最新就是1.20.0，github release失误，已处理！

**Comment by hhiew** [comment]
> @pizixi 可否提供具体的操作以及进程日志？
> 
> 1. pmon2 版本？
> 2. 具体操作步骤？
> 3. 进程日志？pmon2 logf [进程id]
> 
> 一般来说手动Kill进程后，pmon2会尝试自动拉起进程（除非你的进程一直重启失败），可以观察整个过程中的进程id，我这边演示没有问题。截图如下： <img alt="WX20220725-233823@2x" width="1312" src="https://user-images.githubusercontent.com/1408202/180819857-34c5f6b9-6ce1-41d3-b5d2-860b61706c9f.png">

我这边也出现了同样的问题.
第一次启动成功.我查看了日志
`root@erptest:/erp/erp# pmon2 log erpserver

(/erp/erp/pkg/forCasbin/Casbin.go:410)
[2022-11-22 14:34:46]  [0.29ms]  SELECT * FROM `action`
[0 rows affected or returned ]

(/erp/erp/repository/system/forUser/UserRep.go:389)
[2022-11-22 14:34:46]  [2.69ms]  SELECT * FROM `user`
[181 rows affected or returned ]
Now listening on: http://0.0.0.0:3698
Application started. Press CTRL+C to shut down.

root@erptest:/erp/erp# pmon2 log erpserver

(/erp/erp/pkg/forCasbin/Casbin.go:410)
[2022-11-22 14:34:46]  [0.29ms]  SELECT * FROM `action`
[0 rows affected or returned ]

(/erp/erp/repository/system/forUser/UserRep.go:389)
[2022-11-22 14:34:46]  [2.69ms]  SELECT * FROM `user`
[181 rows affected or returned ]
Now listening on: http://0.0.0.0:3698
Application started. Press CTRL+C to shut down.
`
这是正常的,我强制kill掉应用进程.就不会再次成功启动.我查日志报找不到.env文件,这个.env是我应用存放的配置文件,看了这边关于绝对路径的说明,感觉和这个有关系
`root@erptest:/erp/erp# kill 2830022
root@erptest:/erp/erp# pmon2 log erpserver
sync.(*Once).Do(...)
        /erp/go/src/sync/once.go:65
erp/boot/ds.SyncDB()
        /erp/erp/boot/ds/Database.go:72 +0x31
erp/boot.AfterShutdown({0xc00054ff50, 0x2, 0xc00054ff60?})
        /erp/erp/boot/Boot.go:62 +0xad
main.main()
        /erp/erp/main.go:38 +0x1c8
2022/11/22 14:35:27 Error loading .env file
2022/11/22 14:35:33 Error loading .env file
`

**Comment by hhiew** [comment]
fork出来后在attr中添加了dir配置,我这边你正常
`lastSepIdx := strings.LastIndex(processFile, string(os.PathSeparator))
	attr := &os.ProcAttr{
		Dir:   processFile[0 : lastSepIdx+1],
		Env:   os.Environ(),
		Files: []*os.File{nil, logOutput, logOutput},
		Sys: &syscall.SysProcAttr{
			Credential: &syscall.Credential{
				Uid: uint32(uid),
				Gid: uint32(gid),
			},
			Setsid: true,
		},
	}`
