### ISSUE TITLE
centos8现在有镜像源了吗

### ISSUE THREAD

**Issue by u5de6** [ntt360/pmon2#3]
RT
目前的http://ntt360.com/rpms访问不了了

**Comment by apptut** [comment]
http://ntt360.com 已迁移至 https://rpm.ntt360.com，请参考文档。

此外，关于centos8, 没有打算构建rpm的计划。因为centos8, 官方的即将废弃。如果你有兴趣，可以直接clone该项目，在centos8下，go build 一份即可。

**Comment by apptut** [comment]
已提供release centos8版本rpm包可下载
