### ISSUE TITLE
deb包无法下载

### ISSUE THREAD

**Issue by limhu** [ntt360/pmon2#4]
Resolving rpm.ntt360.com (rpm.ntt360.com)... 49.232.26.249
Connecting to rpm.ntt360.com (rpm.ntt360.com)|49.232.26.249|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://rpm.ntt360.com [following]
--2021-07-06 13:10:50--  https://rpm.ntt360.com/
Connecting to rpm.ntt360.com (rpm.ntt360.com)|49.232.26.249|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-07-06 13:10:50 ERROR 403: Forbidden.

**Comment by Error996** [comment]
自己编译下啊
[release.zip](https://github.com/ntt360/pmon2/files/7175650/release.zip)
mkdir -p /usr/local/pmon2/bin/
mkdir -p /etc/pmon2/config
mkdir /var/log/pmon2
mkdir /var/run/pmon2
压缩包里的三个程序丢到/usr/local/pmon2/bin/
配置文件丢到/etc/pmon2/config，github里有

**Comment by apptut** [comment]
@limhu 之前提供过deb，但ubuntu平台我看是systemd可以实现管理。可以用rpm包转deb工具。然后同样使用systemd启动。目前来看deb需求不多，后续看反馈再跟进。
